### ISSUE TITLE
Importing file into Blender

### ISSUE THREAD

**Issue by BagietaDC** [gyoerkaa/nvx2loader#4]
Hi! I have a problem, when I'm trying to import a file (I'm selecting the file in format .nvx2) it's doing nothing. Can someone help me?

**Comment by gyoerkaa** [comment]
I'll need to file in question to be sure. 

Also: Is there any error/output in Blender's console? You can toggle it by: Window => Toggle System Console (in Blender's main window)

**Comment by BagietaDC** [comment]
I'm importing it from City Car Driving.

**Comment by BagietaDC** [comment]
It's showing nothing in the console about file or addon

**Comment by gyoerkaa** [comment]
I've downloaded some nvx2 files for that. They all cause the same problem, not loading the header correctly.

I'll try to fix it.

**Comment by gyoerkaa** [comment]
I've released a [new version](https://github.com/gyoerkaa/nvx2loader/releases/tag/release2.1), which will load those files.

There are multiple nvx2 file versions: One for nebula device 2 (which your files are using) and the newer v3. The difference is the the Specification of vertex format, which is 4 bytes in the header. The only way to detect the version is to try and load it and subsequently fail.

There is an auto-detect setting for the version, but I don't know how reliable it is. If it fails, you can force a specific version in the top left of Blender's import screen with the engine version setting.

**Comment by BagietaDC** [comment]
Thaanks! It's working now
